#ifndef PQC_PAKE_NICE_PAKE_H
#define PQC_PAKE_NICE_PAKE_H

void PQC_PAKE_NICE_PAKE_A1();

void PQC_PAKE_NICE_PAKE_B1();

void PQC_PAKE_NICE_PAKE_A2();

void PQC_PAKE_NICE_PAKE_RE_A1();

void PQC_PAKE_NICE_PAKE_RE_B1();

void PQC_PAKE_NICE_PAKE_RE_A2();

#endif
